//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SongRequestManagerV2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_kansai {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_kansai() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SongRequestManagerV2.Properties.Resource.kansai", typeof(Resource_kansai).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to あかんリスト.
        /// </summary>
        internal static string BUTTON_BLACK_LIST {
            get {
                return ResourceManager.GetString("BUTTON_BLACK_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ひすとりーみますわ.
        /// </summary>
        internal static string BUTTON_HISTORY {
            get {
                return ResourceManager.GetString("BUTTON_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ほな、やるで.
        /// </summary>
        internal static string BUTTON_PLAY {
            get {
                return ResourceManager.GetString("BUTTON_PLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to とじてまっせ.
        /// </summary>
        internal static string BUTTON_QUEUE_CLOSE {
            get {
                return ResourceManager.GetString("BUTTON_QUEUE_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to あいてまっせ.
        /// </summary>
        internal static string BUTTON_QUEUE_OPEN {
            get {
                return ResourceManager.GetString("BUTTON_QUEUE_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to もういっぺん.
        /// </summary>
        internal static string BUTTON_REPLAY {
            get {
                return ResourceManager.GetString("BUTTON_REPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to きゅーに戻しますわ.
        /// </summary>
        internal static string BUTTON_REQUESTS {
            get {
                return ResourceManager.GetString("BUTTON_REQUESTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to とばすわ.
        /// </summary>
        internal static string BUTTON_SKIP {
            get {
                return ResourceManager.GetString("BUTTON_SKIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to とばすわ.
        /// </summary>
        internal static string BUTTON_SKIP_ALL {
            get {
                return ResourceManager.GetString("BUTTON_SKIP_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 履歴を確認しまっせ.
        /// </summary>
        internal static string HOVERHINT_HISTORY {
            get {
                return ResourceManager.GetString("HOVERHINT_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 現在のキューの一覧に戻りまっせ.
        /// </summary>
        internal static string HOVERHINT_REQUESTS {
            get {
                return ResourceManager.GetString("HOVERHINT_REQUESTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ダウンロードの進捗やねん.
        /// </summary>
        internal static string TEXT_DOWNLOAD_PROGRESS {
            get {
                return ResourceManager.GetString("TEXT_DOWNLOAD_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ひすとりーですわ.
        /// </summary>
        internal static string TEXT_FLOWCORDINATER_TITLE_HISTORY {
            get {
                return ResourceManager.GetString("TEXT_FLOWCORDINATER_TITLE_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to きゅーですわ.
        /// </summary>
        internal static string TEXT_FLOWCORDINATER_TITLE_QUEUE {
            get {
                return ResourceManager.GetString("TEXT_FLOWCORDINATER_TITLE_QUEUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゲーム中おとなしくしますわ.
        /// </summary>
        internal static string TEXT_PEFORMANCE_MODE {
            get {
                return ResourceManager.GetString("TEXT_PEFORMANCE_MODE", resourceCulture);
            }
        }
    }
}
