//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SongRequestManagerV2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_SimplifiedChinese_AprilFools {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_SimplifiedChinese_AprilFools() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SongRequestManagerV2.Properties.Resource.SimplifiedChinese.AprilFools", typeof(Resource_SimplifiedChinese_AprilFools).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 禁忌列表.
        /// </summary>
        internal static string BUTTON_BLACK_LIST {
            get {
                return ResourceManager.GetString("BUTTON_BLACK_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 过往.
        /// </summary>
        internal static string BUTTON_HISTORY {
            get {
                return ResourceManager.GetString("BUTTON_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 战斗.
        /// </summary>
        internal static string BUTTON_PLAY {
            get {
                return ResourceManager.GetString("BUTTON_PLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 拒绝挑战.
        /// </summary>
        internal static string BUTTON_QUEUE_CLOSE {
            get {
                return ResourceManager.GetString("BUTTON_QUEUE_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接受挑战.
        /// </summary>
        internal static string BUTTON_QUEUE_OPEN {
            get {
                return ResourceManager.GetString("BUTTON_QUEUE_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 东山再起.
        /// </summary>
        internal static string BUTTON_REPLAY {
            get {
                return ResourceManager.GetString("BUTTON_REPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 战书.
        /// </summary>
        internal static string BUTTON_REQUESTS {
            get {
                return ResourceManager.GetString("BUTTON_REQUESTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无视.
        /// </summary>
        internal static string BUTTON_SKIP {
            get {
                return ResourceManager.GetString("BUTTON_SKIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 歌颂征战沙场英雄事迹.
        /// </summary>
        internal static string HOVERHINT_HISTORY {
            get {
                return ResourceManager.GetString("HOVERHINT_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 书写保家卫国历史篇章.
        /// </summary>
        internal static string HOVERHINT_REQUESTS {
            get {
                return ResourceManager.GetString("HOVERHINT_REQUESTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 杀气.
        /// </summary>
        internal static string TEXT_DOWNLOAD_PROGRESS {
            get {
                return ResourceManager.GetString("TEXT_DOWNLOAD_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 丰功伟绩.
        /// </summary>
        internal static string TEXT_FLOWCORDINATER_TITLE_HISTORY {
            get {
                return ResourceManager.GetString("TEXT_FLOWCORDINATER_TITLE_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 战场.
        /// </summary>
        internal static string TEXT_FLOWCORDINATER_TITLE_QUEUE {
            get {
                return ResourceManager.GetString("TEXT_FLOWCORDINATER_TITLE_QUEUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一心一意.
        /// </summary>
        internal static string TEXT_PEFORMANCE_MODE {
            get {
                return ResourceManager.GetString("TEXT_PEFORMANCE_MODE", resourceCulture);
            }
        }
    }
}
